config/routes.rb
Rails.application.routes.draw do
  root :to => "login#login"
  get 'sign_up/signup'
  post 'sign_up/newUser' => 'sign_up#newUser'
  get 'login/check' => 'login#check'
  get 'login/login'
  get 'calendar/calendar'
  get 'lectures/lectures'
  get 'announcement/hello'
  # get 'announcement/announcement'
  get 'discussion/discussion'
  get 'exams/exams'
  get 'assignments/assignments'
  get 'modules/modules'
  get 'announcement/hello'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'user/login' => 'user#login'
  get '/user/index', to: "user#login"
  get '/assignment/student', to: "assignment#student"
  get '/assignment/feedback', to: "assignment#feedback"
  get '/assignment/admin' => 'assignment#admin'
  patch '/assignment/update' => 'assignment#update'
  get '/user/export_csv' => 'user#export_csv'
  post '/assignment/admin/(:id)' => 'assignment#admin'
  post '/assignment/student/(:id)' => 'assignment#student'
  get '/assignment/admin/(:id)' => 'assignment#admin'

  resources :student_mark
  resources :assignment
  resources :course
  resources :user
  resources :changelogs, only: :index

  resources :assignment do
    match "same" => 'assignment#same', :via => [:get, :post]

  end

end

app/controllers/sign_up_controller.rb
# todo currently not used as is not a user story but tested functions and works as intended
class SignUpController < ApplicationController
  def user_params
    params.permit(:name, :studentid, :password, :email)
  end

  # Function name: SignUpController.signup()
  # Summary: Is not currently called.
  #
  def signup
  end

  # Function name: SignUpController.newUser()
  # Summary: Is not currently called.
  #          It calls User.create(object) and redirects to signup page
  #
  def newUser
    User.create(user_params)
    redirect_to '/sign_up/signup'
  end

end #end of SignUpController.class

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/views/sign_up/signup.html.erb
<h1>SignUp#signup</h1>

<p>Find me in app/views/sign_up/signup.html.erb</p>

<%= form_with model: @user, url: sign_up_newUser_path(@user) ,html: { class: "ui form" }, method: :post do |form| %>

  <div class="field">
    <%= form.label :name%>
    <%= form.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :studentid%>
    <%= form.text_field :studentid %>
  </div>
  <br>
  <div class="field">
    <%= form.label :email%>
    <%= form.text_field :email%>
  </div>
  <br>
  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password%>
  </div>
  <br>
  <br>
  <div class="actions">
    <%= form.submit "SIGN UP", name: "submit", class: "ui primary button"%>
  </div>
<% end %>
<div class="ui basic buttons">
  <%= link_to login_login_url , class: "ui button" do %>
    <i class="chevron left icon"></i> Back
  <% end %>
</div>