config/routes.rb
Rails.application.routes.draw do
  root :to => "login#login"
  get 'sign_up/signup'
  post 'sign_up/newUser' => 'sign_up#newUser'
  get 'login/check' => 'login#check'
  get 'login/login'
  get 'calendar/calendar'
  get 'lectures/lectures'
  get 'announcement/hello'
  # get 'announcement/announcement'
  get 'discussion/discussion'
  get 'exams/exams'
  get 'assignments/assignments'
  get 'modules/modules'
  get 'announcement/hello'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'user/login' => 'user#login'
  get '/user/index', to: "user#login"
  get '/assignment/student', to: "assignment#student"
  get '/assignment/feedback', to: "assignment#feedback"
  get '/assignment/admin' => 'assignment#admin'
  patch '/assignment/update' => 'assignment#update'
  get '/user/export_csv' => 'user#export_csv'
  post '/assignment/admin/(:id)' => 'assignment#admin'
  post '/assignment/student/(:id)' => 'assignment#student'
  get '/assignment/admin/(:id)' => 'assignment#admin'

  resources :student_mark
  resources :assignment
  resources :course
  resources :user
  resources :changelogs, only: :index

  resources :assignment do
    match "same" => 'assignment#same', :via => [:get, :post]

  end

end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :course
  has_one :mark
  has_many :tasks
  has_many :users, through: :tasks

  def self.student
    #Task.includes(:assignment, :user, :mark).where(studentid: 'a1781637')
    Task.includes(:assignment , :user, :mark).where(user_id: 4)
    #@details = Task.includes(:assignment , :user, :mark).all
  end

  def self.averageassgrade()
    sum = Mark.where(asstype: "Assignment").sum(:mark)
    num = Mark.where(asstype: "Assignment").all.count
    if num!=0
    sum/num
    end
  end

  def self.averageexamgrade()
    sum = Mark.where(asstype: "Exam").sum(:mark)
    num = Mark.where(asstype: "Exam").all.count
    if num!=0
      sum/num
    end
  end

  def self.averagecurrentgrade(id)
    sum = Task.includes(:mark).where(assignment_id: id).sum(:mark)
    #sum=Mark.where(task_id: id).sum(:mark)
    num = Task.includes(:mark).where(assignment_id: id).count
    if num!=0

      sum/num
    end
  end

  def self.same(id)
    userid=Task.includes(:user_id).where(assignment_id: id)
    Task.includes(:assignment , :user, :mark).where(user_id: userid)

  end

  def self.userid(id)
    Task.includes(:user_id).where(assignment_id: id).all

  end



  def self.student(studentid)
    Task.includes(:assignment , :user, :mark).where(user_id: User.select(:id).where(studentid: studentid))
  end

  def self.admin(id)
    #Task.includes(:assignment , :user, :mark).find_by_id(id: session)

    #Task.includes(:assignment , :user, :mark).all

    if id == -1
      Task.includes(:assignment , :user, :mark).all
    else
      Task.includes(:assignment , :user, :mark).where(assignment_id: id)
    end
    #Task.includes(:assignment , :user, :mark).find_by(id: id)
    #if session == -1
      #@assignment = Task.includes(:assignment , :user, :mark).all
      #@allassignments = Assignment.all
      #@allassignments = Task.includes(:assignment , :user, :mark).all

      #else
      #@allassignments = Task.includes(:assignment , :user, :mark).all
      #@assignment = Task.includes(:assignment , :user, :mark).find_by(assignment_id: session)
      #@assignment = Task.includes(:assignment , :user, :mark).all
      #@allassignments = Assignment.all
      #end
  end


  #def self.create(assignment_params)
    #Assignment.create(assignment_params)
    # self.Assignment.new
  #end

  def edit
    session[:id] = params[:id]
  end

  def show
  end

  def self.update(id , params)
     assignment = Mark.find_by(task_id: id)
     params[:mark] = params[:mark].to_i
     return if params[:mark] < 0 || params[:mark] > 100


     if params[:mark] < 50 && params[:mark] >= 0
       grade = "F"
       elsif params[:mark] >= 50 && params[:mark] < 65
       grade = "P"
       elsif params[:mark] >= 65 && params[:mark] < 75
       grade = "C"
       elsif params[:mark] >= 75 && params[:mark] < 85
       grade = "D"
       elsif params[:mark] >= 85 && params[:mark] <= 100
       grade = "HD"
     end
     if assignment
       assignment.update(mark: params[:mark], comment: params[:comment], grade: grade)
     else
       Mark.create(task_id: id, grade: grade, mark: params[:mark], comment: params[:comment], asstype: "Assignment")
     end




  end

  def destroy
    #respond_to do |format|
    #  format.html { redirect_to href="/admin", notice: "Student submission was successfully removed from the Database."}
    #  format.json { head :no_content }
    #end
  end

  #def assignment_params
    #params.permit(:courseid, :assignmentid, :assignmentname, :assignmentdescr, :grade, :mark, :comments)
  #params.permit(:course_id, :assignmentname, :assignmentdesc, :weight)
  #end

end

app/controllers/assignment_controller.rb
class AssignmentController < ApplicationController
  def assignment_params
    params.permit(:course_id, :assignmentname, :assignmentdesc, :weight, :mark, :comment, :id, :grade)
  end

  # Function name: AssignmentController.student()
  # Summary: It gets called by visiting assignment/student.html
  #          After passing role check, populates students assignments
  #
  def student
    if session[:role] != 1
      redirect_to root_url
    end
    puts "student.html +++++++++++++++++++++++++++++++++++++++"
    @studentid = session[:user]
    @assignment = Assignment.student(@studentid)
  end


  # Function name: AssignmentController.admin()
  # Summary: It gets called by visiting admin.html
  #          After passing role check, populates the cc students and related assignments
  #
  def admin
    if session[:role] != 2
      redirect_to root_url
    end
    parameters = params[:id]
    @averageassgrade = Assignment.averageassgrade()
    @averageexamgrade = Assignment.averageexamgrade()
    if params.has_key?(:id)
      @assignment = Assignment.admin(parameters)
      if @assignment == nil
      end
      @title = ""
      @assignment.each do |help|
        @title = help.assignment.assignmentname
      end
      @currentassignment = @title
      @averagecurrentgrade = Assignment.averagecurrentgrade(parameters)
    else
      @assignment = Assignment.admin(-1)
      @currentassignment = "All Assignments"
    end
    params[:id] = nil
  end


  def same
    parameters = params[:id]
    @assignment = Assignment.same(parameters)
    @userid = Assignment.userid(parameters)

  end


  # Function name: AssignmentController.create()
  # Summary: Currently is not called as not a user story
  #          creates a new assignment from parameters
  #
  def create
    Assignment.create(assignment_params)
  end


  # Function name: AssignmentController.edit()
  # Summary: Currently is not called as not a user story
  #          creates a new assignment from parameters
  #
  def edit
    session[:id] = params[:id]
  end


  # Function name: AssignmentController.show()
  # Summary: Currently is not called, placeholder only
  #
  def show
  end



  def update
    params[:id] = session[:id]
    Assignment.update(params[:id], assignment_params)
     respond_to do |format|
        format.html do
       redirect_to '/assignment/admin'
        end
     end
  end

  def destroy
    @assignments.destroy
    #respond_to do |format|
    # format.html { redirect_to href="/admin", notice: "Student submission was successfully removed from the Database."}
    # format.json { head :no_content }
    #end
  end

end #end of AssignmentController.class

app/helpers/assignment_helper.rb
module AssignmentHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignment/_feedbackform.html.erb
<%= form_with model: @assignment , url: assignment_update_path(@assignment) , html: { class: "ui form" }, method: :patch do |form| %>


  <div class="field">
    <%= form.label :feedback %>
    <%= form.text_area :feedback %>
  </div>

  <div class="actions">
    <%= form.submit class: "ui primary button" , name: 'submit' %>
  </div>
<% end %>

app/views/assignment/_form.html.erb
<%= form_with model: @assignment , url: assignment_update_path(@assignment) , html: { class: "ui form" }, method: :patch do |form| %>

  <div class="field">
    <%= form.label :mark %>
    <%= form.text_field :mark, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit class: "ui primary button" , name: 'submit' %>
  </div>
<% end %>

app/views/assignment/admin.html.erb
<div class="pusher">
    <div class="ui basic segment">
      <h3 class="ui header"></h3>

      <div>
        <div class = "ui message">
          <p></p>
          <h1 class="ui info header">
            <i class="user md icon"></i>
            Course Coordinator View
          </h1>

          <p>The Course Coordinator View allows the quick selection of Assignments through the dropdown menu. After
          selection, the corresponding marks will appear in the table below.</p>
          <!--
          <div class="ui selection dropdown">
            <input type="hidden" name=“assignment”>
            <i class="dropdown icon"></i>
            <div class="default text">assignment</div>
            <div class="menu">
              <div class="item" data-value=“EXAM”>EXAM</div>
              <div class="item" data-value=“ASSIGNMENT”>ASSIGNMENT</div>
              <div class="item" data-value=“TUTORIAL”>TUTORIAL</div>
              <div class="item" data-value=“WORKSHOP”>WORKSHOP</div>
            </div>
          </div>

          -->


          <div class="ui form">
            <div class="field">
              <label>Assignment</label>
              <!-- <= form_tag(assignment_admin_url(id: assignment.id)) do -%>
                <= select_tag "id", options_for_select(Assignment.all.collect {|p| [ p.assignmentname, p.id ]}, selected: :id) %>
                  <= submit_tag "SUBMITTT" %>
                < end %>
                -->
              <%= form_tag assignment_admin_url(id: params[:id]), method: "post" do %>
                <!-- <= select("assignmentname", "id", Assignment.all.collect {|p| [ p.assignmentname, p.id ]}, {:selected => @sigh}, { include_blank: true }) %> -->
                <%= select_tag "id", options_for_select(Assignment.all.collect {|p| [ p.assignmentname, p.id ]}, selected: :id , include_blank: true) %>
                <!-- <= collection_select(:id, :assignmentname, Assignment.all, :id, :assignmentname) %> -->
                <!-- <= select("assignmentname", "id", Assignment.all.collect {|p| [ p.assignmentname, p.id ]}, {:selected => params[:id]}, { include_blank: true }) %> -->
                <!-- <= select_tag "assignment", options_for_select(@haha, :selected) %> -->
                <!-- < puts 'KANYE WEST++++' %>
                  < puts :selected %> -->
                <!-- <select label="assignment" class="ui search dropdown">
                  < @assignment.each do |assignment| %>
                      <option> name: <= assignment.assignment.assignmentname %> < @ok = assignment.assignment.id %></option>
                  < end %>
                </select>
                -->
                <%= submit_tag "Submit" , class: 'ui button'  %>
              <% end %>
              <% params[:id] = nil %>
            </div>
          </div>


          <p>Average Assignments Grade (All): <%= @averageassgrade %></p>
          <p>Average Exam Grade (All): <%= @averageexamgrade %></p>

          <% if @averagecurrentgrade %>
            <p>Average Grade for <%=@currentassignment %>: <%= @averagecurrentgrade %></p>
          <% end %>

          <% if @currentassignment == "All Assignments"%>
            <h3>Assignment: <%= @currentassignment %> </h3>
          <% else %>
            <h3>Assignment: <%= @currentassignment %></h3>
          <% end %>
          <%= link_to( 'Export all marks as CSV', user_export_csv_path(format: "csv", :class => 'btn-ex')) %>
          <table class="ui purple striped table aligned text-break wrapped" style="word-wrap: break-word;flex: inherit">
            <thead>
            <tr>
              <th>Student ID</th>
              <th>Student Name</th>
              <th>Comments</th>
              <th>Mark</th>
              <th>Grade</th>
              <th>Title</th>
              <th class="aligned"></th>
            </tr>
            </thead>
            <tbody>
            <% @assignment.each do |assignment| %>
              <tr>
                <td><%= assignment.user.studentid %></td>
                <td>

                  <div data-tooltip = "See all work submitted by <%=assignment.user.name %>">
                    <%=link_to assignment_same_path(assignment.id), class: "ui floated small basic labeled icon" do %>
                     <%= assignment.user.name %>
                     <i class="user icon"></i>
                    <%end %>

                  </div>
                </td>
                <td><p id= "wrap" style="word-break":"break-all;"><%= assignment.mark&.comment %></p></td>
                <td><p><%= assignment.mark&.mark %></p></td>
                <td><p><%= assignment.mark&.grade %></p></td>
                <td><p><%= assignment.assignment.assignmentname %></p></td>
                <td class="left aligned">
                  <div class="ui small basic buttons">
                    <%= link_to "#", class: "ui mini button" do %>
                      <i class="eye icon"></i>
                    <% end %>
                    <%= link_to edit_assignment_path(assignment), class: "ui mini button" do %>
                      <i class="edit outline icon"></i>
                    <% end %>
                    <%= link_to "#", method: :destroy, data: { confirm: 'Are you sure?' }, class: "ui mini button" do %>
                      <i class="cancel icon"></i>
                    <% end %>
                  </div>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>

          <br>

        </div>

      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/assignment/edit.html.erb
<h1 class="ui header">
  Editing Grade
</h1>

<%= render 'form', assignment: @assignments %>

<div class="ui basic buttons">
  <%= link_to assignment_admin_url , class: "ui button" do %>
    <i class="chevron left icon"></i> Back
  <% end %>
</div>

app/views/assignment/feedback.html.erb
<div class="ui bottom attached segment pushable">
<h1>

</h1>
<h1 class="ui header">
  Feedback for Student:
</h1>

  <p>The student has requested for feedback! Please insert more comprehensive feedback below.</p>

<%= render 'feedbackform', assignment: @assignments %>

<div class="ui basic buttons">
  <%= link_to assignment_admin_url , class: "ui button" do %>
    <i class="chevron left icon"></i> Back
  <% end %>
</div>

<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

</div>

app/views/assignment/same.html.erb
<div class="pusher">
    <div class="ui basic segment">
      <h3 class="ui header"></h3>
      <div>
        <div class = "ui message">
          <p></p>
          <h1 class="ui info header">
            <i class="user md icon"></i>
            Course Coordinator View for Student: <%= %>
          </h1>
          <p>Average Assignments Grade (Student): <%= @averageassgrade %></p>
          <p>Exam Grade (Student): <%= @averageexamgrade %></p>

          <% if @averagecurrentgrade %>
            <p>Average Grade for <%=@currentassignment %>: <%= @averagecurrentgrade %></p>
          <% end %>
          
          <%= link_to( 'Export all marks as CSV', user_export_csv_path(format: "csv", :class => 'btn-ex')) %>
          <table class="ui purple striped table aligned text-break wrapped" style="word-wrap: break-word;flex: inherit">
            <thead>
            <tr>
              <th>Comments</th>
              <th>Mark</th>
              <th>Grade</th>
              <th>Name</th>
              <th class="aligned"></th>
            </tr>
            </thead>
            <tbody>
            <% @assignment.each do |assignment| %>
              <tr>
                <td><p id= "wrap" style="word-break":"break-all;"><%= assignment.mark.comment %></p></td>
                <td><p><%= assignment.mark.mark %></p></td>
                <td><p><%= assignment.mark.grade %></p></td>
                <td><p><%= assignment.assignment.assignmentname %></p></td>
                <td class="left aligned">
                  <div class="ui small basic buttons">
                    <%= link_to "#", class: "ui mini button" do %>
                      <i class="eye icon"></i>
                    <% end %>
                    <%= link_to edit_assignment_path(assignment), class: "ui mini button" do %>
                      <i class="edit outline icon"></i>
                    <% end %>
                    <%= link_to "#", method: :destroy, data: { confirm: 'Are you sure?' }, class: "ui mini button" do %>
                      <i class="cancel icon"></i>
                    <% end %>
                  </div>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>

          <br>

        </div>

      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/assignment/student.html.erb
<div class="pusher">
  <div class="ui basic segment">
      <div>
        <div class = "ui message">
          <h1 class="ui info header">
            <i class="user icon"></i>
            <%= @studentid %>
          </h1>
          <p></p>


          <!--
          Assignment
          <div class="ui selection dropdown">
            <input type="hidden" name=“assignment”>
            <i class="dropdown icon"></i>
            <div class="default text">assignment</div>
            <div class="menu">
              <div class="item" data-value=“EXAM”>EXAM</div>
              <div class="item" data-value=“ASSIGNMENT”>ASSIGNMENT</div>
              <div class="item" data-value=“TUTORIAL”>TUTORIAL</div>
              <div class="item" data-value=“WORKSHOP”>WORKSHOP</div>
            </div>
          </div>
          -->

          <!--
          <div class="ui form">
            <div class="field">
              <label>Assignment</label>
               <= form_tag(assignment_admin_url(id: assignment.id)) do -%>
                <= select_tag "id", options_for_select(Assignment.all.collect {|p| [ p.assignmentname, p.id ]}, selected: :id) %>
                  <= submit_tag "SUBMITTT" %>
                < end %>
                -->
          <!--
              <= form_tag assignment_student_url(id: params[:id]), method: "post" do %> -->
                <!-- <= select("assignmentname", "id", Assignment.all.collect {|p| [ p.assignmentname, p.id ]}, {:selected => @sigh}, { include_blank: true }) %> -->
                <!-- <= select_tag "id", options_for_select(Assignment.all.collect {|p| [ p.assignmentname, p.id ]}, selected: :id , include_blank: true) %> -->
                <!-- <= collection_select(:id, :assignmentname, Assignment.all, :id, :assignmentname) %> -->
                <!-- <= select("assignmentname", "id", Assignment.all.collect {|p| [ p.assignmentname, p.id ]}, {:selected => params[:id]}, { include_blank: true }) %> -->
                <!-- <= select_tag "assignment", options_for_select(@haha, :selected) %> -->

                <!-- <select label="assignment" class="ui search dropdown">
                </select>
                -->
          <!--
                <= submit_tag "Submit" , class: 'ui button'  %>
              < end %>
              < params[:id] = nil %>
            </div>
          </div> -->

          <h3>Student ID: <%= @myid %></h3>

          <h2>Results and Submissions</h2>


          <table class="ui blue table " style="max-width:700px;">
            <thead>
            <tr>
              <th>Assignment</th>
              <th>Comments</th>
              <th>Mark</th>
              <th>Grade</th>
              <th class="right aligned"></th>
              <th class="right aligned"></th>
            </tr>
            </thead>
            <tbody>
            <% @assignment.each do |assignment| %>
              <tr>
                <td><%= assignment.assignment.assignmentname %></td>
                <td><p id= "wrap" style="word-break":"break-all;"><%= assignment.mark.comment %></p></td>
                <td><p><%= assignment.mark.mark %></p></td>
                <td><p><%= assignment.mark.grade %></p></td>
              <td class="left aligned">
                <div class="ui small basic buttons">
                  <%= link_to "#", class: "ui mini button" do %>
                    <i class="bullhorn icon"></i> Request Feedback
                  <% end %>
                </div>
              </td>
                <td class="left aligned">
                  <div class="ui small basic buttons">
                    <%= link_to "#", class: "ui mini button" do %>
                      <i class="bullhorn icon"></i> Request Remark
                    <% end %>
                  </div>
                </td>
            </tr>
            <% end %>
            </tbody>
          </table>

          <br>

        </div>
      </div>
    </div>
  </div>
</div>
</div>

<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>