config/routes.rb
Rails.application.routes.draw do
  root :to => "login#login"
  get 'sign_up/signup'
  post 'sign_up/newUser' => 'sign_up#newUser'
  get 'login/check' => 'login#check'
  get 'login/login'
  get 'calendar/calendar'
  get 'lectures/lectures'
  get 'announcement/hello'
  # get 'announcement/announcement'
  get 'discussion/discussion'
  get 'exams/exams'
  get 'assignments/assignments'
  get 'modules/modules'
  get 'announcement/hello'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'user/login' => 'user#login'
  get '/user/index', to: "user#login"
  get '/assignment/student', to: "assignment#student"
  get '/assignment/feedback', to: "assignment#feedback"
  get '/assignment/admin' => 'assignment#admin'
  patch '/assignment/update' => 'assignment#update'
  get '/user/export_csv' => 'user#export_csv'
  post '/assignment/admin/(:id)' => 'assignment#admin'
  post '/assignment/student/(:id)' => 'assignment#student'
  get '/assignment/admin/(:id)' => 'assignment#admin'

  resources :student_mark
  resources :assignment
  resources :course
  resources :user
  resources :changelogs, only: :index

  resources :assignment do
    match "same" => 'assignment#same', :via => [:get, :post]

  end

end

app/helpers/annoucement_helper.rb
module AnnoucementHelper
end

app/views/annoucement/hello.html.erb
<div class="ui visible inverted left vertical sidebar menu">
  <%=image_tag("gallery/uniadelaide.jpg",  :size => "260x200", :align => "left")%>


  <%= link_to href="/assignment/admin", class:"ui secondary button" do%> Course Coordinator View
    <i class="user md icon"></i>
  <% end %>

  <%= link_to href="/assignment/student", class:"ui secondary button" do%>
    Student View
    <i class="user icon"></i>
  <% end %>

  <div><p>
    .
  </p></div>


  <i class="grey bullhorn icon"></i>
  <button class="ui inverted grey button"><%= link_to "ANNOUNCEMENT", annoucement_hello_path %></button>


  <a class="item">
  </a>

  <i class="blue book icon"></i><button class="ui inverted primary button"><%= link_to "MODULES", modules_modules_path %></button>

  <a class="item">
  </a>

  <i class="green edit icon"></i>
  <button class="ui inverted green button"><%= link_to "ASSIGNMENTS", assignments_assignments_path %></button>

  <a class="item">
  </a>

  <i class="red clipboard icon"></i>
  <button class="ui inverted red button"><%= link_to "EXAMS", exams_exams_path %></button>

  <a class="item">
  </a>

  <i class="orange comment icon"></i>
  <button class="ui inverted orange button"><%= link_to "DISCUSSION", discussion_discussion_path %></button>

  <a class="item">
  </a>

  <i class="yellow video icon"></i>
  <button class="ui inverted yellow button"><%= link_to "LECTURES", lectures_lectures_path %></button>

  <a class="item">
  </a>

  <i class="pink calendar icon"></i>
  <button class="ui inverted pink button"><%= link_to "CALENDAR", calendar_calendar_path %></button>

  <a class="item">
  </a>
  <i class="blue file alternate icon"></i>
  <button class="ui inverted blue button"><%= link_to "changelog", changelog_changelog_path %></button>

</div>


<h1>Announcement#hello</h1>
<p>Find me in app/views/announcement/hello.html.erb</p>

announcement